# Generated by Django 4.1.2 on 2022-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
