# Generated by Django 4.1.2 on 2022-12-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tomeet_date_of_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateTimeField(),
        ),
    ]
