# Generated by Django 4.1.2 on 2022-12-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tomeet_date_of_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateTimeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
